# Generated by Django 2.1.3 on 2019-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(default='2019-07-13'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='2019-07-13', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(),
        ),
    ]
